package com.example.kevin.commands;

import android.app.Activity;
import android.content.pm.ResolveInfo;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.TextView;

import java.util.List;

/**
 * Created by Kev94 on 18.08.2015.
 */

//ArrayAdapter that contains a list of possible suggestions that are made when the app is confronted
// with an unknown command and the user responds with 'correct' either according to occurrences of
// words that are part of an existing command or with the help of the database that keeps track of
// confusions of commands (e.g. 'open email' was often corrected to 'open browser' -> 'open browser
// will be one of the suggestions); the elements will be put into the adapter and a view is created
public class SuggestionListAdapter extends ArrayAdapter {

    private final Activity mContext;
    Object[] mSuggestions;
    //how often was the unknown command replaced by this command when the command was repeated or
    // corrected by the user
    List<Integer> mFrequencies;

    //constructor takes the suggestions and the frequencies that were generated by the SuggestionGenerator
    // class as input arguments
    public SuggestionListAdapter(Activity context, Object[] suggestions, List<Integer> frequencies) {

        super(context, R.layout.suggestion_list, suggestions);
        mContext = context;
        mSuggestions = suggestions;
        mFrequencies = frequencies;
    }

    //create the view of the adapter; see suggestion_list.xml for the layout; each row has the same
    //layout, but contains different suggestions
    @Override
    public View getView(int position, View view, ViewGroup parent) {

        LayoutInflater inflater = mContext.getLayoutInflater();

        View rowView = inflater.inflate(R.layout.suggestion_list, null, true);

        TextView suggestionNumber = (TextView) rowView.findViewById(R.id.suggestion_number);
        TextView suggestionName = (TextView) rowView.findViewById(R.id.suggestion_name);
        TextView suggestionFrequency = (TextView) rowView.findViewById(R.id.suggestion_frequency);

        suggestionNumber.setText(Integer.toString(position+1));
        suggestionName.setText((String)mSuggestions[position]);
        suggestionFrequency.setText(mContext.getString(R.string.suggestion_frequency, mFrequencies.get(position)));

        return rowView;
    }
}
